
let etudiantsSerialises = [(name:"Elliott", section: "Littéraire", moyenne: 16.0),
                            (name:"Amélie", section: "Scientifique", moyenne: 12.5),
                            (name:"Noémie", section: "Littéraire", moyenne: 8.0),
                            (name:"Thierry", section: "Economie", moyenne: 19.0),
                            (name:"Karim", section: "Littéraire", moyenne: 11.0),
                            (name:"Frédéric", section: "Scientifique", moyenne: 10.0),
                            (name:"William", section: "Scientifique", moyenne: 10.5),
                            (name:"John", section: "Economie", moyenne: 14.5),
                            (name:"Mélissa", section: "Littéraire", moyenne: 19.0),
                            (name:"Conor", section: "Littéraire", moyenne: 16.5),
                            (name:"Théo", section: "Economie", moyenne: 3.0),
                            (name:"Sébastien", section: "Scientifique", moyenne: 18.0),
                            (name:"Patricia", section: "Littéraire", moyenne: 20.0),
                            (name:"Carole", section: "Littéraire", moyenne: 6.0),
                            (name:"Anthony", section: "Economie", moyenne: 9.0),
                            (name:"Mickaêl", section: "Economie", moyenne: 15.0),
                            (name:"Laurent", section: "Scientifique", moyenne: 17.0),
                            (name:"Stéphane", section: "Littéraire", moyenne: 11.0),
                            (name:"Martin", section: "Economie", moyenne: 18.0),
                            (name:"Colette", section: "Littéraire", moyenne: 10.0),
                            (name:"Yann", section: "Scientifique", moyenne: 14.0)]